apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name:  "{{ .scyllaDBMonitoringName }}-alerts"
  labels:
    scylla-operator.scylladb.com/scylladbmonitoring-name: "{{ .scyllaDBMonitoringName }}"
spec:
  {{- .groups | nindent 2 }}
