apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: "{{ .scyllaDBMonitoringName }}-table"
  labels:
    scylla-operator.scylladb.com/scylladbmonitoring-name: "{{ .scyllaDBMonitoringName }}"
spec:
  {{- .groups | nindent 2 }}
