# Version information
scyllaImage:
  tag: 6.2.0
agentImage:
  tag: 3.4.0@sha256:441403aed8880cad1feef68aa7a8ee9ffd99a458dc1dcff3dc54ce5bf3cb07b7
# Cluster information
developerMode: true
datacenter: us-east-1
racks:
  - name: us-east-1b
    members: 2
    storage:
      capacity: 5Gi
      storageClassName: scylladb-local-xfs
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 1
        memory: 1Gi
