# Namespace where the Scylla Cluster will be created
apiVersion: v1
kind: Namespace
metadata:
  name: scylla
---
# Scylla Cluster
apiVersion: scylla.scylladb.com/v1
kind: ScyllaCluster
metadata:
  name: scylla-cluster
  namespace: scylla
spec:
  agentVersion: 3.3.3@sha256:40e31739e8fb1d48af87abaeaa8ee29f71607964daa8434fe2526dfc6f665920
  version: 6.2.0
  sysctls:
    - fs.aio-max-nr=2097152
  datacenter:
    name: us-east-1
    racks:
      - name: a
        members: 1
        storage:
          storageClassName: scylladb-local-xfs
          capacity: 1800G
        resources:
          limits:
            cpu: 7
            memory: 56G
        placement:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: topology.kubernetes.io/zone
                      operator: In
                      values:
                        - us-east-1a
                    - key: scylla.scylladb.com/node-type
                      operator: In
                      values:
                        - scylla
          tolerations:
            - key: role
              operator: Equal
              value: scylla-clusters
              effect: NoSchedule
      - name: b
        members: 1
        storage:
          storageClassName: scylladb-local-xfs
          capacity: 1800G
        resources:
          limits:
            cpu: 7
            memory: 56G
        placement:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: topology.kubernetes.io/zone
                      operator: In
                      values:
                        - us-east-1b
                    - key: scylla.scylladb.com/node-type
                      operator: In
                      values:
                        - scylla
          tolerations:
            - key: role
              operator: Equal
              value: scylla-clusters
              effect: NoSchedule
      - name: c
        members: 1
        storage:
          storageClassName: scylladb-local-xfs
          capacity: 1800G
        resources:
          limits:
            cpu: 7
            memory: 56G
        placement:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: topology.kubernetes.io/zone
                      operator: In
                      values:
                        - us-east-1c
                    - key: scylla.scylladb.com/node-type
                      operator: In
                      values:
                        - scylla
          tolerations:
            - key: role
              operator: Equal
              value: scylla-clusters
              effect: NoSchedule
